FINALALT1/money-bridge

src/app/globals.css

#4 
- 모바일 기준으로 globals.css 크기 세팅 완료
- 추후 웹 버전 공개됨에 따라 코드 수정 예정

Design: Layout 컴포넌트 크기 세팅

---

src/components/common/TopNav.tsx

#5 
- Top Navigation Bar 제작
1. 뒤로가기 버튼 구현
2. 닫기 버튼은 props를 받아 이동
3. title에도 string type의 props를 받아 render

Feat: TopNav 제작

---

package.json
src/app/globals.css
src/components/common/LocationCard.tsx
src/components/common/TopNav.tsx
yarn.lock

closed #13 
- form에서 사용되는 input의 스타일을 global에서 정의

Feat: Form input style 구현

---

src/components/common/BlurModal/index.tsx
src/components/common/FixedButton/index.tsx
src/components/common/PBCard/index.tsx
src/components/common/PostCard/index.tsx
src/constants/enum.ts

Conf: enum 작성

---

src/components/common/TopNav.tsx

- components 변수명 교체로 인해 page에서 error 발생
- vercel 배포 오류로 인해 변수명 원복

closePath 변수명을 path로 변경

---

public/assets/images/check.svg
src/app/findEmail/page.tsx
src/components/loginPage/KeepLoginButton.tsx

Login page에 로그인 상태 유지하기 체크박스 추가

---

src/app/findPassword/page.tsx
src/components/common/LocationCard.tsx

지도 컴포넌트에서 닫기버튼 삭제

---

src/app/globals.css
src/app/reservation/page.tsx
src/components/reservationPage/BubbleSection.tsx
src/components/reservationPage/EditProfileModal.tsx
src/components/reservationPage/ForwardingModal.tsx
src/components/reservationPage/ModalLayout.tsx
src/components/reservationPage/SelectTimeModal.tsx
src/components/reservationPage/TimeSelect.tsx
tailwind.config.js

#71 
global.css, tailwind.config.js에 맞춰 상담 예약 페이지 스타일링

상담 예약 페이지 스타일링

---

src/app/analysis/page.tsx
src/app/globals.css
src/app/reservation/page.tsx
src/components/common/Navbar.tsx
src/components/reservationPage/SelectCalendar.tsx
src/components/reservationPage/SelectTimeModal.tsx
src/types/reservation.ts

closed #71 
- 상담 예약 페이지에서 상담 신청 버튼 누르면 부자연스럽게 화면 넘어가는 문제
- 달력에서 일정 선택 기본 값 오늘에서 기본값 없음으로 변경, 선택을 직접 해야만 다음 버튼 활성화
- main 태그 좌우 padding 설정

상담 예약 페이지 버그 수정 및 main 태그 스타일링

---

src/app/analysis/complete/page.tsx
src/app/analysis/page.tsx
src/app/globals.css
src/app/reservation/complete/page.tsx
src/components/analysisPage/QuestionSection.tsx
src/components/reservationPage/BubbleSection.tsx
src/store/analysisStore.ts
src/types/analysis.ts
src/utils/convertAnswer.ts

closed #55  
투자 성향 분석 페이지 채팅 기능 구현
분석 완료 버튼 누르면 점수 계산 후에 api 요청, 완료 페이지로 이동

투자 성향 분석 페이지 기능 구현

---

src/app/apis/services/etc.ts
src/app/my/editInfo/[slug]/page.tsx
src/app/my/editInfo/page.tsx
src/app/my/page.tsx
src/app/my/propensity/page.tsx
src/components/common/ResetPasswordForm.tsx
src/components/myPage/editInfoPage/EditInfoForm.tsx
src/components/myPage/propensityPage/HydratePropensity.tsx
src/components/myPage/propensityPage/PropensityChart.tsx
src/hooks/useMyPageCheck.ts
src/types/common.ts

#118 
- 비밀 번호 재설정 기능
- 공지사항, FAQ api 쿼리 파라미터 수정
- 투자성향 보기 에러 처리

마이페이지 API 연결 작업

---

src/app/globals.css
src/app/my/page.tsx
src/app/not-found.tsx
src/app/pblist/page.tsx
src/app/pblist/recommend/page.tsx
src/components/common/Card/CardItem/PBCardSkeletonItem.tsx
src/components/common/Card/CardList/PbCardList.tsx
src/components/myPage/EditProfilePage/EditProfileForm.tsx
src/components/myPage/EditProfilePage/formSections/CompanyInput.tsx
src/components/myPage/EditProfilePage/formSections/FigureInput.tsx
src/components/myPage/EditProfilePage/formSections/IntroInput.tsx
src/components/myPage/EditProfilePage/formSections/MsgInput.tsx
src/components/myPage/PBInfo.tsx
src/components/myPage/serviceCenterPage/AccordianItem.tsx
src/components/myPage/serviceCenterPage/AccordianList.tsx
src/components/pblistPage/FilteredPbCardList.tsx
src/components/pblistPage/PBMenu.tsx
src/hooks/useEditProfile.ts
src/hooks/useGetFilteredPBList.ts
src/hooks/useMyPageCheck.ts
src/types/editProfile.ts
src/utils/cookies.ts

closed #148 
- 무한스크롤 들어가는 카드들 로딩 시 스켈레톤 UI 처리
- 유효하지 않은 페이지 접근 시 404페이지 처리
- EditProfile에서 지점 선택 시 바로 안되는 문제, msg,intro input length 반영 안되는 문제 해결

스켈레톤 UI, 404페이지, EditProfile 버그 수정

---

src/app/globals.css
src/components/common/DoubleInputForm.tsx
src/components/common/ResetPasswordForm.tsx
src/components/common/TopNav.tsx
src/components/joinPage/common/SetPasswordForm.tsx

- 디자인 수정 및 TopNav 로그아웃 추가
- input clear버튼 이미지 추가
- TopNav 로그인 유/무에 따른 버튼 변경

디자인 수정 및 TopNav 로그아웃 추가

---

src/app/apis/services/auth.ts
src/app/management/page.tsx
src/app/schedule/changeTime/page.tsx
src/app/schedule/page.tsx
src/components/common/Navbar.tsx
src/components/common/TopNav.tsx
src/components/mainPage/PbListSection.tsx
src/hooks/useGetUserInfo.ts

#167 
- 메인페이지 불필요한 로그인 유무 API 요청 코드 수정
- 로그인 유무에 따른 네브바 수정
- 컨텐츠 섹션 성향테스트에 따른 조건부 렌더링

메인페이지 QA Error 코드 수정

---

src/hooks/useWithdraw.ts

closed #178 
회원 탈퇴 완료 시 쿠키에 리프레시 토큰, 액세스 토큰 삭제 및 모든 queryClient 데이터 삭제 처리

회원탈퇴 시 Error 코드 수정

---

src/app/my/propensity/page.tsx

#170 
투자성향 페이지로 이동할 때 마이페이지로 리다이렉트 되는 에러 수정

투자성향 페이지로 이동할 때 마이페이지로 리다이렉트 되는 에러 수정

---

src/app/analysis/page.tsx
src/app/my/editInfo/layout.tsx
src/hooks/useGetReservationPageData.ts

closed #170 
투자성향 페이지, 상담예약 페이지 이탈 후 재접속 시 store 리셋 처리

투자성향 페이지, 상담예약 페이지 이탈 후 재접속 시 store 처리

---

src/app/join/pb/[slug]/page.tsx
src/app/join/user/[slug]/page.tsx
src/app/login/[slug]/page.tsx
src/app/login/page.tsx
src/components/common/Navbar.tsx
src/components/loginPage/KeepLoginButton.tsx

- Cookie 차단 시와 로그인 되어있을때의 redirect 구현
- Cookie 차단되어있으면 alert와 redirect
- 로그인 상태이면 로그인 및 회원가입 진입시 redirect

Cookie 차단 시와 로그인 되어있을때의 redirect 구현

---

src/app/findEmail/[...slug]/layout.tsx
src/app/findPassword/[...slug]/layout.tsx
src/app/join/layout.tsx
src/app/login/layout.tsx

- 각 페이지 메타데이터 타이틀 설정
<!— 스크린샷이 필요한 과제면 스크린샷을 첨부해주세요 —>
<!— 참고할 사항이 있다면 적어주세요 —>

로그인,회원가입 이메일/비밀번호 찾기 메타데이터 설정

---

src/app/my/page.tsx
src/app/my/terms/page.tsx
src/components/common/ResetPasswordForm.tsx
src/hooks/useLogin.ts
src/hooks/useMyPageCheck.ts

closed #185 
- 미로그인 상태에서 마이페이지 접근 시 로그인 페이지로 리다이렉트. 그 후에 로그인하고 마이페이지 접근 시 또 로그인 페이지로 리다이렉트 되는 에러 수정

로그인 시 마이페이지 접근 안되는 에러 수정

---

src/app/myCounseling/newReservation/[slug]/page.tsx
src/components/common/Navbar.tsx
src/components/common/TopNav.tsx
src/components/joinPage/pb/ModalCompanyList.tsx
src/components/mainPage/SearchLocation.tsx
src/components/pbdetailPage/pbreviewPage/PbReviewList.tsx
src/hooks/useGeoLacation.tsx
src/types/location.ts

#190 
- 도로명 주소 검색시 카카오 API Error 해결
- 나의 후기 페이지 후기리스트 없을 시 예외처리 반영

위치검색시 도로명주소 관련 Error 수정 그외 기타

---

src/app/my/page.tsx
src/hooks/useMyPageCheck.ts

마이페이지 접근 안되는 문제 해결

---

src/components/joinPage/pb/ModalCompanyList.tsx
src/components/joinPage/pb/SelectCompany.tsx
src/components/myPage/EditProfilePage/formSections/CompanyInput.tsx

증권사리스트를 미리 불러와서 props로 전달

---

src/hooks/useMyPageCheck.ts

 마이페이지 연결 안되는 문제 해결

---

src/app/my/page.tsx
src/hooks/useMyPageCheck.ts
src/middleware.ts

마이페이지 리다이렉트 문제 해결, middleware 의존성 삭제

마이페이지 리다이렉트 문제 해결, middleware 의존성 삭제

---

src/app/my/page.tsx
src/hooks/useMyPageCheck.ts

Fix: 마이 페이지 접근 문제 해결

---

src/components/joinPage/common/JoinInformation.tsx
src/components/joinPage/pb/PbComplete.tsx
src/components/joinPage/user/UserComplete.tsx

인풋 클리어 버튼 추가

---

src/app/join/user/[slug]/page.tsx

유저 회원가입 완료 페이지에서는 redirect X

---

src/components/common/Card/CardItem/ContentCardItem.tsx

Design: 로고 css 수정

---

src/app/apis/services/pb.ts
src/app/bookmark/content/page.tsx
src/app/bookmark/pb/page.tsx
src/app/contents/[slug]/page.tsx
src/app/contents/edit/[slug]/page.tsx
src/app/contents/write/layout.tsx
src/app/contents/write/page.tsx
src/components/common/Card/CardItem/PbCardItem.tsx
src/components/common/Card/CardList/ContentCardList.tsx
src/components/contentsPage/Comments.tsx
src/components/contentsPage/Content.tsx
src/components/contentsPage/Poster.tsx
src/components/contentsPage/Write.tsx
src/components/pbdetailPage/About.tsx
src/components/searchPage/Search.tsx
src/hooks/useContentDelete.ts

임시저장 등록, 컨텐츠 작성, 수정 기능 추가

---

src/app/apis/services/pb.ts
src/app/contents/[slug]/page.tsx
src/app/contents/write/page.tsx
src/app/detail/info/[slug]/page.tsx
src/components/common/Card/CardItem/ContentCardItem.tsx
src/components/contentsPage/Write.tsx
src/components/pbdetailPage/pbreviewPage/PbReviewList.tsx

[Feat: 버튼에 따른 api 호출 추가](https://github.com/FINALALT1/money-bridge/commit/df5aa0341f60abd1eb128fc873b73eaa9fa8cda8)
- 수정하기 -> 컨텐츠 수정하기/임시저장 컨텐츠 등록하기
- 취소 -> 수정하기를 통해 들어온 컨텐츠 페이지로 이동
- 임시저장 -> 컨텐츠 임시저장하기
- 작성완료 -> 컨텐츠 등록하기

Write 컴포넌트 수정

---

next.config.js

#208 
변경된 저장소 경로에 따른 next.config.js 수정

변경된 저장소 경로에 따른 next.config.js 수정

---

next.config.js

closed #209 
next.config.js domain에서 https 삭제

next.config.js domain에서 https 삭제

---

src/app/layout.tsx

KAKAO API beforeInteractive 속성 삭제

---

src/components/managementPage/changeReservationPage/CalendarModal.tsx
src/components/managementPage/changeReservationPage/TimeModal.tsx

#127 
- 예약 일정 변경시 모달 z-index수정

모달 z-index 수정

---

src/app/apis/services/etc.ts
src/components/pblistPage/FilteredPbCardList.tsx
src/hooks/useGetFilteredPBList.ts

closed #228 
store 값 감지하여 location이 바뀔 때마다 useQuery refetch 처리

위치 바뀔 때마다 거리순 PB리스트 refetch

---

src/app/apis/services/location.ts
src/hooks/useGeoLacation.tsx
src/store/location.ts

#217 
- 위치지정시 위도, 경도 스토어에 리셋되는 현상 해결

Fix: 위치지정시 위도, 경도 스토어에 리셋되는 현상 해결

---

src/hooks/useGeoLacation.tsx
src/store/location.ts

Fix: 위치 지정시 에러 수정

---

next.config.js

Chore: proxy 설정
Chore: proxy 설정

Chore: proxy 설정

---

next.config.js
src/app/apis/axios.ts

Feat: API 주소 연결 처리(CORS 에러 우회)

Feat: API 주소 연결 처리(CORS 에러 우회)

---

src/app/sitemap.ts
src/components/contentsPage/Write.tsx
src/components/myPage/serviceCenterPage/AccordianItem.tsx
src/components/pbdetailPage/Intro.tsx
src/components/pbdetailPage/Profile.tsx

- 공지사항, FAQ html 태그 보이는 문제 수정
- 변경된 도메인에 따라 sitemap 변경
- PB 프로필 배경 변경

공지사항, FAQ html 태그 보이는 문제 수정

---

src/app/globals.css
src/app/layout.tsx
src/components/common/Footer.tsx

#245 
- footer 하단 고정
- notice, 번호 수정

Footer 내용 및 스타일 수정

---

src/components/mainPage/AdminButtonSection.tsx
src/components/pblistPage/FilteredPbCardList.tsx

변경된 어드민 URL에 따른 관리자페이지 버튼 링크 수정

변경된 어드민 URL에 따른 관리자페이지 버튼 링크 수정

---

src/app/layout.tsx

오픈그래프 데이터 추가

---

src/app/layout.tsx

트위터, 오픈 그래프 속성 metadata 객체로 이동

트위터, 오픈 그래프 속성 metadata 객체로 이동

---

src/app/contents/edit/[slug]/page.tsx
src/components/contentsPage/Write.tsx

Fix: 경로 수정

---

src/app/detail/content/[slug]/page.tsx
src/components/contentsPage/Content.tsx

Fix: 본인 여부 확인 수정

---

src/app/apis/services/auth.ts
src/app/globals.css
src/components/contentsPage/ContentEditor.tsx
src/components/contentsPage/Reply.tsx
src/components/contentsPage/Write.tsx
src/hooks/useLogout.ts

closed #262 
장시간 로그인 시 로그아웃 에러 수정
컨텐츠 에디터 툴바 수정, 태그1, 태그2 required 처리
대댓글 프로필 이미지 수정
fixed button z-index 수정

QA 에러 및 버그 수정

---

src/components/contentsPage/Content.tsx
src/components/contentsPage/Write.tsx
src/components/pbdetailPage/Intro.tsx
src/hooks/useContentBookMark.ts
src/hooks/usePbBookMark.ts

- 북마크 안되는 문제 수정
- 글 작성 시 태그 필수입력 값에서 제외 (API 추후 수정 예정)

북마크 안되는 문제 수정

---

src/components/common/Card/CardItem/ContentCardItem.tsx
src/components/contentsPage/Content.tsx
src/hooks/useLogout.ts

500 에러 (이미 로그아웃한 액세스 토큰입니다)발생 시에 쿠키 값 삭제 처리
tag2가 있을 때에만 태그 구분자 삽입

로그아웃 관련 에러 수정

---

src/components/mainPage/SearchLocation.tsx

불필요한 로직 제거

---

src/components/common/TopNav.tsx
src/hooks/useGeoLacation.tsx

Fix: 현재위치 적용 이슈

---

src/app/layout.tsx

robots 속성 추가
generateMetadata로 변경

메타데이터 속성 추가

---

src/app/layout.tsx

Fix: metadata 관련 에러 수정

---

src/app/layout.tsx

Fix: head 태그 안에 자체적으로 meta 태그 추가

Fix: head 태그 안에 자체적으로 meta 태그 추가

---

src/app/apis/services/location.ts
src/app/layout.tsx
src/app/reservation/complete/page.tsx
src/components/common/TopNav.tsx
src/components/mainPage/SelectLocationModal.tsx
src/constants/topNavOptions.ts

상담 재신청 후 이동경로 수정

---

src/app/layout.tsx
src/app/pblist/layout.tsx
src/app/pblist/page.tsx

메인페이지가 CSR로 동작되는 에러 수정

---

src/components/common/Card/CardItem/ContentCardItem.tsx

콘텐츠 카드 증권사 로고 사이즈 조절

---

src/app/layout.tsx

Suspense 위치 수정

---

src/components/common/Modal/BlurModal.tsx

Link 경로 수정

---

src/components/common/Card/CardItem/ContentCardItem.tsx

Fix: 북마크 아이콘 변동 안되는 버그 수정
일반 사용자 일때 pb 콘텐츠 북마크가 북마크 시 아이콘이 실시간으로 변동되지 않는 버그를 수정했습니다

Fix: 북마크 아이콘 변동 안되는 버그 수정

---

src/hooks/useContentBookMark.ts

Fix: delete 안되는 버그 수정
콘텐츠에서 북마크 해제가 안되는 버그 수정

Fix: delete 안되는 버그 수정

---

src/app/layout.tsx
src/hooks/useLogout.ts

로그아웃 에러 문제 수정

---

src/components/common/Card/CardItem/PbCardItem.tsx
src/components/pbdetailPage/Intro.tsx
src/hooks/usePbBookMark.ts

Fix: pb페이지에서 북마크 등록/해제 후 정보, 콘텐츠 탭 이동시 반영안되는 버그 수정
isRefetch를 통해 refetchQueries가 필요하면 동작하여 쿼리 무효화가 진행, 북마크 등록/해제가 화면에 반영되게 수정

Fix: pb페이지에서 북마크 등록/해제 후 정보, 콘텐츠 탭 이동시 반영안되는 버그 수정

---

src/components/reservationPage/TimeSelect.tsx
src/components/reservationPage/UserBubble/UserBubble.tsx
src/utils/timeSelectOptions.ts

상담 종료 시간이 새벽을 넘어가는 경우의 경우 처리 및 레이아웃 간격

상담 종료 시간이 새벽을 넘어가는 경우의 경우 처리 및 레이아웃 간격 수정

---

src/utils/timeSelectOptions.ts

<!— 관련있는 이슈 번호(#000)을 적어주세요.
해당 pull request merge와 함께 이슈를 닫으려면
closed #Issue_number를 적어주세요 —>
<!— 과제에 대한 설명을 적어주세요 —>
<!— 스크린샷이 필요한 과제면 스크린샷을 첨부해주세요 —>
<!— 참고할 사항이 있다면 적어주세요 —>

Fix: 타임 관련 에러 수정

---

src/components/managementPage/changeReservationPage/TimeModal.tsx

Fix: 예약 변경시 시간 지정 예외처리 추가

---

src/components/reservationPage/TimeSelect.tsx
src/utils/timeSelectOptions.ts

- consultEnd가 consultStart보다 작은 경우 수정
- 상담 시간 옵션이 많을 경우, 스크롤 처리

Fix: 상담 시간 선택 관련 에러 수정

---

src/app/layout.tsx

Feat: 애널리틱스 Script 추가

---

package.json
src/app/_app.tsx
src/app/layout.tsx
yarn.lock

Feat: 네이버 애널리틱스 추가 설정

---

src/components/myPage/EditProfilePage/AwardForm.tsx
src/components/myPage/EditProfilePage/CareerForm.tsx
src/components/myPage/EditProfilePage/EditProfileForm.tsx
src/components/myPage/EditProfilePage/formSections/AwardsInput.tsx
src/components/myPage/EditProfilePage/formSections/CareerInput.tsx
src/components/myPage/EditProfilePage/formSections/CareersInput.tsx
src/components/myPage/EditProfilePage/formSections/CompanyInput.tsx
src/components/myPage/EditProfilePage/formSections/FigureInput.tsx
src/components/myPage/EditProfilePage/formSections/IntroInput.tsx
src/components/myPage/EditProfilePage/formSections/MsgInput.tsx
src/components/myPage/EditProfilePage/formSections/PortfolioInput.tsx
src/components/myPage/EditProfilePage/formSections/ProfileInput.tsx
src/types/editProfile.ts

PB 프로필 form을 react-hook-form의 FromProvider로 감싼 뒤, form methods props 제거 후 중첩 input 내에서 useFormContext로 필요한 메서드 호출

PB 프로필 form FromProvider 사용

---

next.config.js
src/app/layout.tsx

Feat: google analytics Script 추가

---

src/app/ReactQueryProvider.tsx
src/app/getQueryClient.tsx
src/app/layout.tsx
src/components/mainPage/CustomListSection.tsx
src/components/mainPage/HydrateCustomList.tsx
src/components/mainPage/HydratePbList.tsx
src/components/mainPage/HydrateStockFirm.tsx
src/components/mainPage/PbListSection.tsx
src/components/mainPage/StockFirmSection.tsx
src/hooks/useGetUserInfo.ts
src/utils/cookies.ts
yarn.lock

```
export const dynamic = "force-dynamic";
```
- layout에 문구 추가 후 SSR 처리
- https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config

CSR로 인한 에러 처리 -> SSR로 수정

---

src/app/layout.tsx
src/app/page.tsx

Fix: CSR로 인한 에러 코드 수정

---

src/app/page.tsx

Feat: ssg -> ssr 테스트

---

src/app/page.tsx

Test: SSG Test

---

src/app/lounge/page.tsx

Test: SSR, revalidate Error test

Test: SSR, revalidate Error test

---

src/app/lounge/page.tsx
src/components/loungePage/Content.tsx
src/components/loungePage/Intro.tsx
src/components/loungePage/PbRecommend.tsx

- client 페이지 server 페이지로 전환 및 컴포넌트 수정
- props 제거 후 컴포넌트 내부에서 유저정보 확인

SSG -> SSR 전환

---

src/components/myPage/serviceCenterPage/AccordianItem.tsx

Style: 공지사항, FAQ에서 list-style 출력

---

src/app/contents/temporary/layout.tsx
src/app/faq/page.tsx
src/app/management/layout.tsx
src/app/my/layout.tsx
src/app/myCounseling/layout.tsx
src/app/notice/page.tsx
src/app/schedule/layout.tsx

#311 
SSG revalidate 관련 에러 수정
- CSR, SSR 페이지 렌더링 SSG로 처리되는 에러 수정

SSG -> SSR전환, revalidate 설정

---

src/app/my/page.tsx

Feat: revalidate Test

---

src/app/schedule/page.tsx

Feat: revalidate 설정

---

package.json
src/app/apis/axios.ts
src/hooks/useLogin.ts
src/hooks/useUserJoin.ts
src/utils/cookies.ts
yarn.lock

- setCookie에서 refreshToken과 동일한 maxAge 설정

Fix: 브라우저 종료 시 액세스토큰 사라지는 문제 해결

---

src/components/myPage/editInfoPage/EditInfoForm.tsx

Fix: 이름 수정 시 버튼 비활성화 문제 수정

---

src/components/common/Card/CardItem/PbCardItem.tsx
src/components/contentsPage/Comments.tsx
src/components/contentsPage/Reply.tsx
src/components/joinPage/common/JoinInformation.tsx
src/utils/pbMyId.ts

- 작성한 댓글 삭제 되도록 연결
- 휴대폰번호 가입 시 중복 체크 후 버튼 활성화

Fix: 신규 오류사항 수정

---

src/components/contentsPage/ContentEditor.tsx
src/hooks/useShare.ts
src/utils/truncateContent.ts

- 컨텐츠 에디터 출력 오류 수정
- 카카오톡 공유하기에 html 태그 출력 에러 수정

Fix: 컨텐츠 에디터, 카카오톡 공유하기 에러 수정

---

src/app/detail/content/[slug]/page.tsx
src/components/contentsPage/Content.tsx
src/components/pbdetailPage/About.tsx

Fix: util 함수 변경에 따른 인수 수정

---

src/utils/truncateContent.ts

Fix: 공백 처리 문제 수정

---

src/hooks/useContentDelete.ts

Fix: 컨텐츠 삭제후 이동 경로 수정

---

src/components/joinPage/pb/BranchCreation.tsx

Feat: 지점 등록 name 값 수정

---

src/app/myCounseling/reviewWrite/[slug]/page.tsx
src/components/joinPage/common/JoinInformation.tsx
src/components/pbdetailPage/Intro.tsx
src/hooks/useShare.ts
src/utils/truncateContent.ts

Fix: 추가 오류 사항 수정
- PB 상세페이지 content없을시 가드 추가
- 휴대폰 중복 확인 후 재확인시 버튼 disabled 대응 추가
- 상담 후기 작성시 상담스타일 미선택시 API요청 되지 않도록 수정

Fix: 추가 오류 사항 수정

---

src/components/joinPage/pb/BranchCreation.tsx
src/components/joinPage/pb/SelectCompany.tsx

Fix: 중복지점 등록시 모달 띄우도록 처리

---

src/components/common/SingleInputForm.tsx
src/components/joinPage/pb/BranchCreation.tsx

Style: 불필요한 코드 제거
빌드 실패 관련 재배포

Style: 불필요한 코드 제거, 빌드 실패 관련 재배포
